model:
  backbone: nano
  version: yolo11
task: detect
training:
  amp: true
  batch: 32
  box: 7.5
  close_mosaic: 10
  cls: 1.5
  dfl: 1.5
  epochs: 6
  imgsz: 640
  lr0: 0.001
  patience: 15
  warmup_epochs: 5
  weight_decay: 0.0005
